# Generated by Django 3.2.14 on 2022-08-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cover_photo',
            field=models.ImageField(upload_to='media/portfolio'),
        ),
    ]
