# Generated by Django 3.2.14 on 2022-08-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_portfolio_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='company_url',
            field=models.URLField(default='https://facebook.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cover_photo',
            field=models.ImageField(upload_to='projects'),
        ),
    ]
